version: '3.7'
services:
  python:
    container_name: ${PROJECT_NAME}
    image: ${PYTHON_IMAGE}
    ports:
      - "5000:5000"
    volumes:
      - ./volumes/flask:/code
    env_file: ./.env
    networks: 
      - python
    entrypoint: /bin/sh
    stdin_open: true
    tty: true

networks:
    python:
      ipam:
        driver: default
        config:
         - subnet: 172.19.0.0/24