version: '3.6'

services:
  python:
    container_name: flask-dev
    build:
      context: .
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./volumes/flask:/app
    environment: 
      - FLASK_ENV=development
    networks: 
      - python

networks:
    python:
      ipam:
        driver: default
        config:
         - subnet: 172.19.0.0/24