version: '3.7'

services:
  python:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      args:
        python_image: ${PYTHON_IMAGE}
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./volumes/flask:/app
    env_file: ./.env
    networks: 
      - python

networks:
    python:
      ipam:
        driver: default
        config:
         - subnet: 172.19.0.0/24